### ISSUE TITLE
New Controlled Vocabulary

### ISSUE THREAD

**Issue by simmlerc** [mwang87/ReDU-MS2-GNPS#234]
Hi, 
Would it be possible to add the following controlled vocabulary in the ReDU Sample Information Template?:
1. SampleTypeSub1: 
- marine_invertebrate (or marine_sponge)
- seawater

2. SampleCollectionMethod:
-liquid-solid phase extraction (polymeric resin)

Thanks a lot for your help!
Cheers

Charlotte

**Comment by alan-jarmusch** [comment]
Hi Charlotte,

I apologize for the very slow response.

I have added the following **SampleTypeSub1** options for your use:
- marine_invertebrates
- water_seawater

I have added the following **SampleCollectionMethod** options for your use:
- liquid, solid phase extraction (polymeric resin)

You will find these options in the latest template - you may have to "make a copy" once again in order to see them, but don't worry - you should be able to copy and paste from your old template without issues.

Sorry again for the delay.
