### ISSUE TITLE
Add not applicable/not specified to the NCBITaxonomy controlled vocabulary?

### ISSUE THREAD

**Issue by oolonek** [mwang87/ReDU-MS2-GNPS#236]
@alan-jarmusch  and Redu team,

How would you deal with such situation:
I want to upload to ReDu a dataset which contains blanks and QC (apparently OK to upload such files since they appear in the SampleType controlled vocabulary)
However how do you fill the mandatory NCBITaxonomy column in this case ? 
I could not find not applicable or not specified in the controlled vocabulary here.

Many thanks,

Pierre-Marie

**Comment by alan-jarmusch** [comment]
Hi,

Sorry for the slow reply.

Yes - you can certainly upload blanks and QCs (in fact we would love to have more of those files).
You can enter any of the following - whichever is more appropriate in your judgement:
- **not applicable**
for example, a blank of extraction solvent
- **not collected**
For example: it is a plant sample, but you don't know the taxonomic name because it wasn't recorded
- **not specified**
For example: it is a plant sample, but you don't know the taxonomic name

I hope this helps!
