### ISSUE TITLE
Additional approved terms (Solvent)

### ISSUE THREAD

**Issue by Ellis-ONeill** [mwang87/ReDU-MS2-GNPS#248]
HI,
Would it be possible to add Butanol (100%) to the approved solvent terms. 
Thanks,
Ellis

**Comment by Ellis-ONeill** [comment]
Could we also add '2071594|Euglena gracilis var. saccharophila' to the available NCBI taxonomies - it is the correct NCBI txid.
Thanks,
Ellis

**Comment by Ellis-ONeill** [comment]
Also '216134|Euglena anabaena var. minor', '161229|Cryptoglena skujai', '38275|Euglena mutabilis' and'2576610|Trachelomonas sp.' in NCBI taxonomies.
Sorry to keep with these,
Ellis

**Comment by mwang87** [comment]
Hi @Ellis-ONeill  Sorry for the delay, its been a busy few months as I'm transition to my new faculty position at UCR. This will include a migration of ReDU and one thing I want to do is a bit of a refactor so that we can make the terms more extensible so even you can propose additions so it becomes way more responsive. Once things are settled later in the summer, lets work together to get this done!

**Comment by alan-jarmusch** [comment]
thanks for the contribution. the validator will be updated.
